# Generated by Django 4.2.13 on 2024-08-26 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvdata",
            name="age",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="country",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="date",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="name",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="sr",
        ),
        migrations.AddField(
            model_name="csvdata",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="csvdata",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "csv_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graphs",
                        to="graph.csvdata",
                    ),
                ),
            ],
        ),
    ]
