# Generated by Django 4.2.13 on 2024-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0002_remove_csvdata_age_remove_csvdata_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="image_base64",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="csvdata",
            name="file",
            field=models.FileField(default="default_file.csv", upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="graph",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
